login/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('', include('login.urls'))
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name='accordion'),
    # dilanjutkan ...
]

story8/urls.py
from django.contrib import admin
from django.urls import path
from .views import searchbook, data

app_name = 'story8'

urlpatterns = [
    path('', searchbook, name='searchbook'),
    path('data/', data, name='data'),
]

login/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your models here.
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import CreateUserForm
import datetime

from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('story7:accordion')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('login:login')

        context = {'form' :form}
        return render(request, 'register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('story7:accordion')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('story7:accordion')
            else:
                messages.info(request, 'username or password is incorrect')

        context = {}
        return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('story7:accordion')

story7/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render(request, 'accordion.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def data(request):
	try:
		q = request.GET['q']

	except:
		q = 'quilting'

	json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q).json()
	return JsonResponse(json_read)
    
def searchbook(request):
	return render(request,'searchbook.html')

login/templates/login.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
 
{% block head %}
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #8a288a !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #c65bf7 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
{% endblock head %}

{% block content %}
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				
				{% for message in messages %}
					<p>{{message}}</p>
				{% endfor %}
				
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'login:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>
{% endblock content %}
</html>

login/templates/register.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>

{% block head %}  
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #8a288a !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #e060af !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
{% endblock head %}

{% block content %}
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                
                {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
{% endblock content %}
</html>

story7/templates/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'accordion.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <title>The Next Journey</title>
{% endblock head %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="boxcolor col-md-4">
            <div class="bd-example">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                  </ol>
                  <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                      <img class="d-block w-100" img src="{% static 'AERP5946.jpg' %}" alt="First slide">
                      <div class="carousel-caption d-none d-md-block">
                        <h3>A few memories of me</h3>
                        <p>A moment lasts all of a second, but the memory lives on forever.</p>
                      </div>
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" img src="{% static 'IMG_2034.JPG' %}" alt="Second slide">
                      <div class="carousel-caption d-none d-md-block">
                        <h3>a few memories of me</h3>
                        <p>A moment lasts all of a second, but the memory lives on forever.</p>
                      </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" img src="{% static 'IMG_5154 (2).JPG' %}" alt="Second slide">
                        <div class="carousel-caption d-none d-md-block">
                          <h3>a few memories of me</h3>
                          <p>A moment lasts all of a second, but the memory lives on forever.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" img src="{% static 'IMG_1739.jpg' %}" alt="Second slide">
                        <div class="carousel-caption d-none d-md-block">
                          <h3>a few memories of me</h3>
                          <p>A moment lasts all of a second, but the memory lives on forever.</p>
                        </div>
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              </div>
            
    </div>

<div class="col-md-8">
    <div class="container">
        <div class="panel-group" id="accordion" >
            <div class="panel panel-info satu" style="margin-bottom:-8px;">
                <div class="panel-heading">
                    <span class = "pull-right">
                        <div class="accordion-buttons col-2 d-flex justify-content-flex">
                          <div class="button-up">
                              <button type="button" id="button-up" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-up"></button>
                          </div>
                          <div class="button-down">
                              <button type="button" id="button-down" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-down"></button>
                          </div>
                        </div>
                      </span>
                  <h4 class="panel-title">
                      <button class="btn btn-link collapsed" type="button" data-parent=#accordion data-toggle="collapse"
                      data-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                      <strong> MY ACTIVITY </strong>
                    </button>
                  </h4>
                </div>
                <div id="collapse1" class="panel-collapse collapse">
                  <div class="panel-body">
                    Sleep and Kuliah
                  </div>
                </div>
              </div>
              <div class="panel panel-success dua" style="margin-bottom:-8px;">
                  <div class="panel-heading">
                      <span class = "pull-right">
                          <div class="accordion-buttons col-2 d-flex justify-content-flex" >
                              <div class="button-up">
                                  <button type="button" id="button-up" data-parent=#accordion class="btn btn-default glyphicon glyphicon-chevron-up" style="border-radius: 50px;"></button>
                              </div>
                              <div class="button-down">
                                  <button type="button" id="button-down" data-parent=#accordion class="btn btn-default glyphicon glyphicon-chevron-down" style="border-radius: 50px;"></button>
                              </div>
                            </div>
                        </span>
                    <h4 class="panel-title">
                        <button class="btn btn-link collapsed" type="button" data-parent=#accordion data-toggle="collapse"
                        data-target="#collapse2" aria-expanded="false" aria-controls="collapse3">
                        <strong> MY EXPERIENCE </strong>
                      </button>
                    </h4>
                  </div>
                  <div id="collapse2" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            Staff Media Partner Compfest and Staff Acara BETIS 2020.
                        </ul>
                    </div>
                  </div>
                </div>
          <div class="panel panel-warning tiga" style="margin-bottom:-8px;">
            <div class="panel-heading">
                <span class = "pull-right">
                    <div class="accordion-buttons col-2 d-flex justify-content-flex">
                        <div class="button-up">
                            <button type="button" id="button-up" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-up"></button>
                        </div>
                        <div class="button-down">
                            <button type="button" id="button-down" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-down"></button>
                        </div>
                      </div>
                  </span>
              <h4 class="panel-title">
                  <button class="btn btn-link collapsed" type="button" data-parent=#accordion data-toggle="collapse"
                  data-target="#collapse3" aria-expanded="false" aria-controls="collapse3">
                  <strong> MY HOBBY </strong>
                </button>
              </h4>
            </div>
            <div id="collapse3" class="panel-collapse collapse">
              <div class="panel-body">
                  <ul>
                      Watching movie or drama and read a novels.
                  </ul>
              </div>
            </div>
          </div>
          <div class="panel panel-danger empat" >
            <div class="panel-heading">
                <span class = "pull-right">
                    <div class="accordion-buttons col-2 d-flex justify-content-flex">
                        <div class="button-up">
                            <button type="button" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-up"></button>
                        </div>
                        <div class="button-down">
                            <button type="button" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-down"></button>
                        </div>
                      </div>
                  </span>
              <h4 class="panel-title">
                  <button class="btn btn-link collapsed" type="button" data-parent=#accordion data-toggle="collapse"
                  data-target="#collapse4" aria-expanded="false" aria-controls="collapse4">
                  <strong> MY FAVORITE MOVIE </strong>
                </button>
              </h4>
            </div>
            <div id="collapse4" class="panel-collapse collapse">
              <div class="panel-body">
                  <ul>
                      Sherlock Holmes, Harry Potter, and Mission Impossible
                    </ul>
              </div>
            </div>
          </div> 
        </div>
</div>
    


<script src="{% static 'accordion.js' %}"></script>
{% endblock content %}

story7/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block head %}
    {% endblock head %}
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  </head>

  <body>
    <div class="fixed-top">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Story
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'story7:accordion' %}">Story 7</a>
          <a class="dropdown-item" href="{% url 'story8:searchbook' %}">Story 8</a>
        </div>
  
      </li>
    </ul>
  </div>
  {% if user and user.is_authenticated %}
  <span id="hello-msg" style="font-size: large;">Hello, {{request.user}}</span>
  <span><a id="Button" href="{% url 'login:logout' %}">logout</a></span>
  {% else %}
  <span><a id="Button" href="{% url 'login:login' %}">login</a></span>
  {% endif%}

</nav>
</div>
        {% block content %}
        {% endblock content %}
  </body>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    
</html>

story8/templates/searchbook.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/searchbook.css' %}" />
    <title>Search Book</title>
{% endblock head %}

{% block content %}
    <div class="SearchBook">
        <div class="d-flex justify-content-center">
            <h1 class="judulSearchBook">
                <b name="judul">Search Book</b>
            </h1>
        </div>
        <div class="SearchBook2">
            <input type="text" id="textField" name="searchbar" placeholder="Search for books.." title="Type in a name">
        </div>
        <div class="table-responsive" id="Table">
            <table class="table table-hover">
                <thead>
                    <tr class="table text-center">
                        <th scope="col" style="color: beige">No</th>
                        <th scope="col" style="color: beige">Cover</th>
                        <th scope="col" style="color: beige">Title</th>
                        <th scope="col" style="color: beige">Authors</th>
                        <th scope="col" style="color: beige">Publisher</th>
                        <th scope="col" style="color: beige">Published Date</th>
                    </tr>
                </thead>
                <tbody id="hasilSearch" style="color: beige;"></tbody>
            </table>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'js/searchbook.js' %}"></script>
{% endblock content %}